### ISSUE TITLE
Show Message -Standard Document NOT available for download

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebEitl1#2]
Show Message -Standard Document NOT available for download on download page of Transmittal.
1. Internal Transmittal
2. Vendor Transmittal [IDMS-Post Order]

**Comment by hariharan-isgec** [comment]
@isgecharish check and confirm

**Comment by 0340LalitGupta** [comment]
![image](https://user-images.githubusercontent.com/37236522/49365882-f01f0380-f70d-11e8-9035-47e76007fe60.png)
