### ISSUE TITLE
Delete PO Child Item, if child Item is deleted in ERP

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebEitl1#6]
**BUG**
When PO is modified and few child Items are freed, to create new Indent & PO to different vendor.
Currently ERP checks for Bill Receipt and does not check  whether QC has been done or packing list is created as these are done in Joomla.
Currently in Joomla child items removed from PO (ERP) are not deleted. So QC or Packing list can be created for those child Items also.
The above may lead inconsistent PO child Items.
**SOLUTION**
1. When QC has been done or Packing list is created in joomla, It will update Flag in ERP against PO child Items, so that it can also be checked in ERP before freeing child item.
2. Update Flag in ERP when Inspection call is raised.
3. Update Flag in ERP when Packing list is created.
4. Sync child items when PO is modified in ERP.
5. When PO is locked in ERP, it should be automatically fetched in Joomla with proper type (Boughtout/Fabricated/Package).

**Comment by hariharan-isgec** [comment]
@0340LalitGupta : Deal child Item qty is set to Zero instead of deletion, which is the practice
